swagger: "2.0"
info: 
  description: mô tả api....
  version: 1.0.1
  title: swagger

paths:
  /api/products:
    get:
      summary: lấy danh sách sản phẩm
      responses:
        "200": 
          description: lấy sản phẩm thành công
        "400":
          description: lấy sản phẩm không thành công
    post:
      summary: Thêm sản phẩm
      responses:
        "200":
          description: Thêm sản phẩm thành công
      parameters:
      - in: "body"
        name: "body"
        description: "Bắt buộc phải có các trường giống bên dưới"
        required: true
        schema: 
          $ref: "#/components/schemas/Product"

# Models
components:
  schemas:
    Product:
      properties:
        _id:
          type: integer
        name:
          type: string
          minLength: 5
        price: 
          type: integer
        category:
          type: string
      required:
        - name
        - price
        - category